### ISSUE TITLE
Not able to run index.js

### ISSUE THREAD

**Issue by chrigu1981** [mhdawson/AlexaMqttBridge#1]
Hello,

would like to use ur bridge but it seems a bit complicated :)

now i get this if i start index.js:
```
Serverlistening on 5000
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: write EPROTO
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:764:14)
```

**Comment by mhdawson** [comment]
Sorry just noticed this, will take a look over the weekend.

**Comment by chrigu1981** [comment]
sorry i did not followup on this. i just had to update the nodejs

**Comment by mhdawson** [comment]
@chrigu1981 ok good to hear, so you got it running ?  If so I'll close the issue.
