### ISSUE TITLE
Missing key.pem

### ISSUE THREAD

**Issue by Mickelin01** [mhdawson/AlexaMqttBridge#3]
A noob really struggling to get this going, hope you can help out. Finally managed to install the bridge after figuring out I first had to install git, npm and node (would have been helpful if mentioned in the instructions...).
I am running mosquitto on a different RPi, no certificates or user/pw. Using tcp:// for the mqtt url in the config.json.
When I run npm start I get the error "no such file or directory, open '/home/pi/node_modules/AlexaMqttBridge/key.pem". Not sure how to proceed. Thankful for any pointers.

**Comment by mhdawson** [comment]
You need to have a certificate for the server (I use lets encrypt).  The private key should be in key.pem and the certificate in cert.pem.  I do see that I missed that in the instructions and I'll try to add it in the next little while.

In terms of the other setup, if you can submit a PR to the  README.md to add the info you would have found useful that would be great.

**Comment by mhdawson** [comment]
Added doc for requirement for key.pem and cert.pem in f616d92b73bb5d7fe549d14522579aa9afb75427

**Comment by mhdawson** [comment]
Going to close this now.
