### ISSUE TITLE
Plain HTTP support

### ISSUE THREAD

**Issue by oklona** [mhdawson/AlexaMqttBridge#4]
Hello. 

I haven't looked through your code, but if there would be an option to use plain HTTP, that would be great. I have my environment behind a content switch, which handles the SSL encryption for me. If it were possible, I would prefer the internal communication between the CS and the Alexa Bridge to be plain HTTP, to ease off the load on the Raspberry PI which will host the bridge :-)

**Comment by john2exonets** [comment]
+1 for HTTP

**Comment by mhdawson** [comment]
That should be pretty straight forward. Changing:

```JavaScript
// start the server
const ssl_options = {
  key: fs.readFileSync(path.join(__dirname, 'key.pem')),
  cert: fs.readFileSync(path.join(__dirname, 'cert.pem'))
}
const server = http.createServer(ssl_options, requestHandler)
```

to 
```JavaScript
// start the server
let options = new Object();
if (!config.nossl) {
  options = {
    key: fs.readFileSync(path.join(__dirname, 'key.pem')),
    cert: fs.readFileSync(path.join(__dirname, 'cert.pem'))  
  }
}
const server = http.createServer(options, requestHandler)
```
Should do the trick.  Would you be able to try that out and then submit a PR?

I suggest the approach above as it does not change the default for existing users (like myself) but gives people the option not to use ssl.

**Comment by oklona** [comment]
Hi! That change seems to do the trick. Obviously, you also need to add the "nossl" directive in config.json that you refer to :-)

I am a complete noob when it comes to Github. I assume "submit a PR" means to go to the "pull request" tab, and somehow paste the verified changes there?

**Comment by mhdawson** [comment]
@oklona to create a PR you need to fork the repository, make the change there and then us the pull request tab to ask that that change be merged into the repository.

**Comment by oklona** [comment]
Thanks! I tried now, and may have done it correctly. Thanks for your help!

**Comment by mhdawson** [comment]
Closing since this was addressed in https://github.com/mhdawson/AlexaMqttBridge/pull/6
