### ISSUE TITLE
Problem in installing

### ISSUE THREAD

**Issue by skyrNa** [mhdawson/AlexaMqttBridge#5]
Hi,
Let's me say I am new with node.js and with github too.
I tried to follow your accurate guide and i successed to create the amazon skill as you suggests. However I can't install your bridge app. In particular on raspberry I installed npm and node.js, but when I try to send your install command some errors appear. Instead on centos OS the installation goes fine. Could you help me?

I list the errors code here:

error not a package /tmp/npm-22183-AZp1za7V/github.com/mhdawson/AlexaMqttBridge.git
error If you need help, you may report this *entire* log,
error including the npm and node versions, at:
error     <http://github.com/npm/npm/issues>
error System Linux 4.14.70-v7+
error command "/usr/bin/node" "/usr/bin/npm" "install" "https://github.com/mhdawson/AlexaMqttBridge.git"
error cwd /tmp/npm-17880-OfaSSWba/github.com/mhdawson
error node -v v8.11.1
error npm -v 1.4.21
error path /tmp/npm-22183-AZp1za7V/github.com/mhdawson/AlexaMqttBridge.git-unpack/package.json
error syscall open
error code ENOENT
error errno -2

thank you
Michele

**Comment by mhdawson** [comment]
It seems to be having a problem (I think ) opening the /tmp/npm-22183-AZp1za7V/github.com/mhdawson/AlexaMqttBridge.git-unpack/package.json file.  Any chance you cloned as one user but are now trying to do the install as a different user that does not have access?

**Comment by skyrNa** [comment]
Hi mhdawson,
Thanks for the response. 
The problem was fixed by updating apt-get repo and then the version of npm.
Now I am able to lunch index.js.
However I have still other problems... 
I understand that alexa skill can ask for service only n port 443, so I need to use a reverse proxy rule to forward the traffic from alexa to my port number (default value 5000), is it correct?



Thks
Michele

**Comment by mhdawson** [comment]
I use port number 5000 internally.  My router forwards my external 443 port to my internal machine where it is running on port 5000.  You'll need to do something similar.

**Comment by skyrNa** [comment]
Done!   it's good working
Thanks

**Comment by mhdawson** [comment]
Great to hear, going to close the issue.
